# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ring2) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(ring1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: -1 }