# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:circle_rune/animations/pause_all
tag @s add aj.circle_rune.animation.fire.playing
scoreboard players set @s aj.fire.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:circle_rune/animations/fire/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only