# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(left_leg) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(head) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(body) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(item_display) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(right_arm) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(item_display1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(left_arm) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(right_leg) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i