# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(horns) {transformation: [-1f,0f,0f,0.25f,0f,0.9222f,0f,1.0764f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0.1875f,0f,0.9222f,0f,1.0764f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0.375f,0f,0.9201f,0.0625f,0.1542f,0f,0.0678f,-0.9977f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,-0.25f,0f,0.9207f,0.0536f,0.199f,0f,0.0581f,-0.9983f,0.1736f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9109f,-0.1443f,0.6153f,0f,-0.1564f,-0.9877f,0.075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9222f,0f,0.5576f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0.1875f,0f,0.9222f,0f,1.0764f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}