# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(horns) {transformation: [-1f,0f,0f,0.25f,0f,0.9833f,0f,1.1146f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0.1875f,0f,0.9833f,0f,1.1146f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0.375f,0f,0.9724f,0.1466f,0.1312f,0f,0.149f,-0.9888f,0.2292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,-0.25f,0f,0.9817f,-0.0572f,0.1312f,0f,-0.0581f,-0.9983f,0.0357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9808f,-0.0702f,0.5726f,0f,-0.0713f,-0.9975f,0.0341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9833f,0f,0.5615f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0.1875f,0f,0.9833f,0f,1.1146f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}