# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(horns) {transformation: [-1f,0f,0f,0.25f,0f,0.9455f,0f,1.0909f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0.1875f,0f,0.9455f,0f,1.0909f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0.375f,0f,0.9455f,0f,0.1455f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,-0.25f,0f,0.9447f,0.0367f,0.1455f,0f,0.0388f,-0.9992f,0.2875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9304f,0.1679f,0.586f,0f,0.1776f,-0.9841f,-0.0852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9455f,0f,0.5591f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0.1875f,0f,0.9455f,0f,1.0909f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}