# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(horns) {transformation: [-1f,0f,0f,0.25f,0f,0.975f,0f,1.1094f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0.1875f,0f,0.975f,0f,1.1094f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0.375f,0f,0.9591f,0.1753f,0.1344f,0f,0.1798f,-0.9837f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,-0.25f,0f,0.9713f,-0.085f,0.1344f,0f,-0.0872f,-0.9962f,0.0536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9694f,-0.1042f,0.5776f,0f,-0.1069f,-0.9943f,0.0511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.975f,0f,0.5609f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0.1875f,0f,0.975f,0f,1.1094f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}