# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(horns) {transformation: [-1f,0f,0f,0.25f,0f,0.9444f,0f,1.0903f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0.1875f,0f,0.9444f,0f,1.0903f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0.375f,0f,0.9409f,0.0823f,0.1983f,0f,0.0872f,-0.9962f,0.1806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,-0.25f,0f,0.9423f,0.0641f,0.1458f,0f,0.0678f,-0.9977f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9444f,0f,0.559f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9435f,0.0412f,0.6181f,0f,0.0436f,-0.999f,-0.0208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0.1875f,0f,0.9444f,0f,1.0903f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}