# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.slash.frame matches 21.. run scoreboard players set @s aj.slash.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.slash.frame
execute at @s run function aj:slash/animations/slash/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.slash.frame 1