# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:slash/animations/pause_all
scoreboard players set @s aj.slash.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:slash/animations/slash/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only