# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:lil_fiend rig_hash set value '529c568c1bb6a453b1dfdcfa952504a0d1083a9af6cb92d26b22a28c3bcbfa93'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.cast.frame dummy