# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(left_leg) start_interpolation set value -1
$data modify entity $(head) start_interpolation set value -1
$data modify entity $(body) start_interpolation set value -1
$data modify entity $(item_display) start_interpolation set value -1
$data modify entity $(right_arm) start_interpolation set value -1
$data modify entity $(item_display1) start_interpolation set value -1
$data modify entity $(left_arm) start_interpolation set value -1
$data modify entity $(right_leg) start_interpolation set value -1