# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(left_leg) ~ ~ ~ ~ ~
$execute as $(left_leg) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head) ~ ~ ~ ~ ~
$execute as $(head) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body) ~ ~ ~ ~ ~
$execute as $(body) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(item_display) ~ ~ ~ ~ ~
$execute as $(item_display) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_arm) ~ ~ ~ ~ ~
$execute as $(right_arm) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(item_display1) ~ ~ ~ ~ ~
$execute as $(item_display1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_arm) ~ ~ ~ ~ ~
$execute as $(left_arm) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_leg) ~ ~ ~ ~ ~
$execute as $(right_leg) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1