# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 run function aj:stargazer/animations/spin/zzz/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.spin.frame
function aj:stargazer/animations/spin/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.spin.frame matches 139 run return run function aj:stargazer/animations/spin/zzz/loop_mode_stop
scoreboard players add @s aj.spin.frame 1