# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(horns) ~ ~ ~ ~ ~
$execute as $(horns) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head) ~ ~ ~ ~ ~
$execute as $(head) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left) ~ ~ ~ ~ ~
$execute as $(left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right) ~ ~ ~ ~ ~
$execute as $(right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left1) ~ ~ ~ ~ ~
$execute as $(left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right1) ~ ~ ~ ~ ~
$execute as $(right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body) ~ ~ ~ ~ ~
$execute as $(body) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1