# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:worm_head"
data modify storage animated_java:temp entry.data.rig_hash set value "160183667e4f9c50e15699da9b4359cb87d47c4b883bc89d57235dc6ddbd208c"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.worm_head.node.fin2] run function aj:worm_head/zzz/summon/as_node/fin2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.fin2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worm_head.node.horn2] run function aj:worm_head/zzz/summon/as_node/horn2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.horn2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worm_head.node.horn] run function aj:worm_head/zzz/summon/as_node/horn
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.horn set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worm_head.node.body] run function aj:worm_head/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worm_head.node.deco] run function aj:worm_head/zzz/summon/as_node/deco
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.deco set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worm_head.node.fin] run function aj:worm_head/zzz/summon/as_node/fin
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.fin set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worm_head.node.pincer2] run function aj:worm_head/zzz/summon/as_node/pincer2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pincer2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worm_head.node.pincer1] run function aj:worm_head/zzz/summon/as_node/pincer1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pincer1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worm_head.node.eyes] run function aj:worm_head/zzz/summon/as_node/eyes
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyes set from storage animated_java:gu out
function aj:worm_head/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:worm_head/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount