# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) { transformation: [-1f,0f,0f,0.1188f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(head) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(item_display) { transformation: [-0.0512f,0.0189f,0.9985f,-0.3438f,0.608f,0.7938f,0.0162f,0.9375f,-0.7923f,0.6079f,-0.0522f,0.375f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right_arm) { transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(item_display1) { transformation: [0.0416f,-0.0269f,0.9988f,0.3594f,-0.676f,-0.7368f,0.0083f,0.9375f,0.7357f,-0.6755f,-0.0488f,-0.375f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left_arm) { transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right_leg) { transformation: [-1f,0f,0f,-0.1187f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }