# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.slash.animation.slash.playing] run function aj:slash/animations/slash/zzz/on_tick
function aj:slash/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name