# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:angel_being"
data modify storage animated_java:temp entry.data.rig_hash set value "b8ae224dd94763ea176089d8b188a1eeba0c1a4220148e63fdc151f97c6b2874"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.angel_being.node.wing3] run function aj:angel_being/zzz/summon/as_node/wing3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.wing3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.angel_being.node.wing4] run function aj:angel_being/zzz/summon/as_node/wing4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.wing4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.angel_being.node.wing1] run function aj:angel_being/zzz/summon/as_node/wing1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.wing1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.angel_being.node.wing2] run function aj:angel_being/zzz/summon/as_node/wing2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.wing2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.angel_being.node.body] run function aj:angel_being/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.angel_being.node.block_display5] run function aj:angel_being/zzz/summon/as_node/block_display5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.angel_being.node.block_display8] run function aj:angel_being/zzz/summon/as_node/block_display8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.angel_being.node.block_display6] run function aj:angel_being/zzz/summon/as_node/block_display6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.angel_being.node.block_display7] run function aj:angel_being/zzz/summon/as_node/block_display7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display7 set from storage animated_java:gu out
function aj:angel_being/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:angel_being/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:angel_being/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount