# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:slash rig_hash set value 'ebd55e93cd823ad0f623465a0f778aafae5a776d42172aa3876a893d5a22fcbd'
scoreboard objectives add aj.slash.frame dummy