# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(bone) ~ ~ ~ ~ ~
$execute as $(bone) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1