# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:stargazer rig_hash set value '3f6156f68adead88c2dc4e7bced04bddee244b8559bcbdb0c9f9725150764cf1'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.slash.frame dummy
scoreboard objectives add aj.stab.frame dummy
scoreboard objectives add aj.spin.frame dummy
scoreboard objectives add aj.teleport.frame dummy