# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:angel_being rig_hash set value 'b8ae224dd94763ea176089d8b188a1eeba0c1a4220148e63fdc151f97c6b2874'
scoreboard objectives add aj.idle.frame dummy