# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(fin2) { transformation: [1f,0f,0f,-0.3125f,0f,1f,0f,0.1875f,0f,0f,1f,-1.4375f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-1.8333f,0f,0f,0.5f,0f,1.8333f,0f,0.1875f,0f,0f,-1.8333f,0.3125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(deco) { transformation: [-1.125f,0f,0f,0.5f,0f,1.125f,0f,0.1875f,0f,0f,-1.125f,0.3125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(fin) { transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.1875f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: -1 }