# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-14.3333f,0f,0f,0f,0f,14.3333f,0f,0f,0f,0f,-14.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function aj:slash/variants/default/apply