# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(wing3) ~ ~ ~ ~ ~
$execute as $(wing3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(wing4) ~ ~ ~ ~ ~
$execute as $(wing4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(wing1) ~ ~ ~ ~ ~
$execute as $(wing1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(wing2) ~ ~ ~ ~ ~
$execute as $(wing2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body) ~ ~ ~ ~ ~
$execute as $(body) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display5) ~ ~ ~ ~ ~
$execute as $(block_display5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display8) ~ ~ ~ ~ ~
$execute as $(block_display8) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display6) ~ ~ ~ ~ ~
$execute as $(block_display6) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display7) ~ ~ ~ ~ ~
$execute as $(block_display7) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1