# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 run function aj:lil_fiend/animations/cast/zzz/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.cast.frame
function aj:lil_fiend/animations/cast/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.cast.frame matches 30.. run return run function aj:lil_fiend/animations/cast/pause
scoreboard players add @s aj.cast.frame 1