# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(left_leg) interpolation_duration set value 1
$data modify entity $(head) interpolation_duration set value 1
$data modify entity $(body) interpolation_duration set value 1
$data modify entity $(item_display) interpolation_duration set value 1
$data modify entity $(right_arm) interpolation_duration set value 1
$data modify entity $(item_display1) interpolation_duration set value 1
$data modify entity $(left_arm) interpolation_duration set value 1
$data modify entity $(right_leg) interpolation_duration set value 1