# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(fin2) ~ ~ ~ ~ ~
$execute as $(fin2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(horn2) ~ ~ ~ ~ ~
$execute as $(horn2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(horn) ~ ~ ~ ~ ~
$execute as $(horn) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body) ~ ~ ~ ~ ~
$execute as $(body) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(deco) ~ ~ ~ ~ ~
$execute as $(deco) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(fin) ~ ~ ~ ~ ~
$execute as $(fin) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(pincer2) ~ ~ ~ ~ ~
$execute as $(pincer2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(pincer1) ~ ~ ~ ~ ~
$execute as $(pincer1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyes) ~ ~ ~ ~ ~
$execute as $(eyes) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1