# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:circle_rune rig_hash set value 'c06b80c11e9ade3a81179c92fcdf3c73b0bcc6cdeaee72d6c45c12081dbbb869'
scoreboard objectives add aj.fire.frame dummy