# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(wing3) { transformation: [-4.5707f,0.3525f,-1.0353f,2f,0.414f,4.1716f,0f,2.5f,1.2247f,-0.0945f,-3.8637f,-3f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(wing4) { transformation: [4.5707f,-0.3525f,-1.0353f,-2f,0.414f,4.1716f,0f,2.5f,1.2247f,-0.0945f,3.8637f,-3f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(wing1) { transformation: [-4.5707f,0.3525f,-1.0353f,2f,0.414f,4.1716f,0f,4.75f,1.2247f,-0.0945f,-3.8637f,-3f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(wing2) { transformation: [4.5707f,-0.3525f,-1.0353f,-2f,0.414f,4.1716f,0f,4.75f,1.2247f,-0.0945f,3.8637f,-3f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-3.3333f,0f,0f,2.0625f,0f,3.3333f,0f,0.5f,0f,0f,-3.3333f,1.3125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(block_display5) { transformation: [-0.2509f,-0.3584f,0f,3.38f,-0.3584f,0.2509f,0f,0.6422f,0f,0f,-8f,3.3125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(block_display8) { transformation: [-0.2509f,-0.3584f,0f,-2.8661f,-0.3584f,0.2509f,0f,5.0157f,0f,0f,-8f,3.3125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(block_display6) { transformation: [-0.2509f,0f,6.5532f,-3.1733f,-0.3584f,0f,-4.5886f,5.2308f,0f,-0.4375f,0f,3.3125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(block_display7) { transformation: [-0.2509f,0f,6.5532f,-3.1733f,-0.3584f,0f,-4.5886f,5.2308f,0f,-0.4375f,0f,-4.25f,0f,0f,0f,1f], start_interpolation: -1 }