# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.lil_fiend.animation.walk.playing] run function aj:lil_fiend/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.lil_fiend.animation.cast.playing] run function aj:lil_fiend/animations/cast/zzz/on_tick
function aj:lil_fiend/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name