# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(fin2) { transformation: [1f,0f,0f,-0.3125f,0f,1f,0f,0.1875f,0f,0f,1f,-1.4375f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(horn2) { transformation: [1f,0f,0f,0.125f,0f,1f,0f,-0.125f,0f,0f,1f,0.1875f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(horn) { transformation: [-1f,0f,0f,0.0625f,0f,1f,0f,-0.125f,0f,0f,-1f,0.25f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-1.375f,0f,0f,0.5f,0f,1.375f,0f,0.1875f,0f,0f,-1.375f,0.3125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(deco) { transformation: [-1.125f,0f,0f,0.5f,0f,1.125f,0f,0.1875f,0f,0f,-1.125f,0.3125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(fin) { transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.1875f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(pincer2) { transformation: [-1f,0f,0f,-0.4502f,0f,1f,0f,0.5625f,0f,0f,-1f,0.7335f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(pincer1) { transformation: [1f,0f,0f,0.2553f,0f,-1f,0f,0.125f,0f,0f,-1f,0.739f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(eyes) { transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.1875f,0f,0f,-1f,0.3125f,0f,0f,0f,1f], start_interpolation: -1 }