# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(horns) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(head) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(left) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(right) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(left1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(right1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(body) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i