# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(horns)
$kill $(head)
$kill $(left)
$kill $(right)
$kill $(left1)
$kill $(right1)
$kill $(body)