# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.stargazer.animation.idle.playing] run function aj:stargazer/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.stargazer.animation.slash.playing] run function aj:stargazer/animations/slash/zzz/on_tick
execute if entity @s[tag=aj.stargazer.animation.stab.playing] run function aj:stargazer/animations/stab/zzz/on_tick
execute if entity @s[tag=aj.stargazer.animation.spin.playing] run function aj:stargazer/animations/spin/zzz/on_tick
execute if entity @s[tag=aj.stargazer.animation.teleport.playing] run function aj:stargazer/animations/teleport/zzz/on_tick
function aj:stargazer/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name