# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(ring2) interpolation_duration set value 1
$data modify entity $(ring1) interpolation_duration set value 1