# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(wing3) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(wing4) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(wing1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(wing2) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(body) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(block_display5) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(block_display8) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(block_display6) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(block_display7) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i