# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.angel_being.animation.idle.playing] run function aj:angel_being/animations/idle/zzz/on_tick
function aj:angel_being/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name