# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(horns) interpolation_duration set value 1
$data modify entity $(head) interpolation_duration set value 1
$data modify entity $(left) interpolation_duration set value 1
$data modify entity $(right) interpolation_duration set value 1
$data modify entity $(left1) interpolation_duration set value 1
$data modify entity $(right1) interpolation_duration set value 1
$data modify entity $(body) interpolation_duration set value 1