# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(horns) start_interpolation set value -1
$data modify entity $(head) start_interpolation set value -1
$data modify entity $(left) start_interpolation set value -1
$data modify entity $(right) start_interpolation set value -1
$data modify entity $(left1) start_interpolation set value -1
$data modify entity $(right1) start_interpolation set value -1
$data modify entity $(body) start_interpolation set value -1