# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.cast.frame matches 31.. run scoreboard players set @s aj.cast.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.cast.frame
execute at @s run function aj:lil_fiend/animations/cast/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.cast.frame 1