# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:stargazer/animations/pause_all
scoreboard players set @s aj.stab.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:stargazer/animations/stab/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only