# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.stargazer.animation.idle.playing
tag @s remove aj.stargazer.animation.slash.playing
tag @s remove aj.stargazer.animation.stab.playing
tag @s remove aj.stargazer.animation.spin.playing
tag @s remove aj.stargazer.animation.teleport.playing