# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(wing3) interpolation_duration set value 1
$data modify entity $(wing4) interpolation_duration set value 1
$data modify entity $(wing1) interpolation_duration set value 1
$data modify entity $(wing2) interpolation_duration set value 1
$data modify entity $(body) interpolation_duration set value 1
$data modify entity $(block_display5) interpolation_duration set value 1
$data modify entity $(block_display8) interpolation_duration set value 1
$data modify entity $(block_display6) interpolation_duration set value 1
$data modify entity $(block_display7) interpolation_duration set value 1