# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(wing3) start_interpolation set value -1
$data modify entity $(wing4) start_interpolation set value -1
$data modify entity $(wing1) start_interpolation set value -1
$data modify entity $(wing2) start_interpolation set value -1
$data modify entity $(body) start_interpolation set value -1
$data modify entity $(block_display5) start_interpolation set value -1
$data modify entity $(block_display8) start_interpolation set value -1
$data modify entity $(block_display6) start_interpolation set value -1
$data modify entity $(block_display7) start_interpolation set value -1