# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(fin2) ~ ~ ~ ~ ~
$execute as $(fin2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body) ~ ~ ~ ~ ~
$execute as $(body) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(deco) ~ ~ ~ ~ ~
$execute as $(deco) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(fin) ~ ~ ~ ~ ~
$execute as $(fin) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1