# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(ring2) ~ ~ ~ ~ ~
$execute as $(ring2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(ring1) ~ ~ ~ ~ ~
$execute as $(ring1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1